"""add news_count and last_response_time to source_stats

Revision ID: add_news_count_cols
Revises: 75c36535602c
Create Date: 2024-03-19 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_news_count_cols'
down_revision = '75c36535602c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_stats', sa.Column('news_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('source_stats', sa.Column('last_response_time', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_stats', 'last_response_time')
    op.drop_column('source_stats', 'news_count')
    # ### end Alembic commands ### 