"""add_proxy_support

Revision ID: c4c0466047c6
Revises: 7261a16ed689
Create Date: 2025-03-25 23:18:57.366890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4c0466047c6'
down_revision = '7261a16ed689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxy_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('protocol', sa.Enum('SOCKS5', 'HTTP', 'HTTPS', name='proxyprotocol'), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ERROR', 'BANNED', name='proxystatus'), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('max_concurrent', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('avg_response_time', sa.Float(), nullable=True),
    sa.Column('last_check_time', sa.DateTime(), nullable=True),
    sa.Column('health_check_url', sa.String(length=512), nullable=True),
    sa.Column('group', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=True),
    sa.Column('successful_requests', sa.Integer(), nullable=True),
    sa.Column('failed_requests', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxy_configs_id'), 'proxy_configs', ['id'], unique=False)
    op.add_column('sources', sa.Column('need_proxy', sa.Boolean(), nullable=True))
    op.add_column('sources', sa.Column('proxy_fallback', sa.Boolean(), nullable=True))
    op.add_column('sources', sa.Column('proxy_group', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'proxy_group')
    op.drop_column('sources', 'proxy_fallback')
    op.drop_column('sources', 'need_proxy')
    op.drop_index(op.f('ix_proxy_configs_id'), table_name='proxy_configs')
    op.drop_table('proxy_configs')
    # ### end Alembic commands ### 